#version: "3.8"
services:
  web:
    build: .
    image: nginx:alpine
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ || exit 1"]
      interval: 10s
      retries: 5
